pipeline{
    agent any
    stages{
        stage("Unit Tests - Backend"){
            steps{
                echo "========executing Backend Tests========"
                dir("bugtracker-backend") {
                    go test -v ./...
                }
            }
           
        }
    }
}